# FROM node:24-alpine

# WORKDIR /app
# COPY package*.json .

# RUN npm install

# COPY . .

# EXPOSE 5173
# CMD ["npm", "run", "dev"]

FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build
RUN npm install -g serve

EXPOSE 5173

CMD ["serve", "-s", "dist", "-l", "5173"]
