services:

  # ─── Postgres for Rails ─────────────────────────────────────────────
  db:
    image: postgres:13
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  # ─── Rails API ───────────────────────────────────────────────────────
  backend:
    build:
      context: ./backend
    env_file: .env
    environment:
      - RAILS_MASTER_KEY
    ports:
      - "3000:80"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db

  # ─── Vite / React Dev Server ────────────────────────────────────────
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"

volumes:
  db_data:
